### ISSUE TITLE
Crash when PHP packages are not installed

### ISSUE THREAD

**Issue by Zarthus** [weechat/weechat#1078]
WeeChat crashes on devel WeeChat 2.0-dev (git: v1.9-353-g157dc811a), the cause is that php7.x-embed is not installed on the system. https://github.com/weechat/weechat/issues/1078#issuecomment-334575574

Original post can be found here, comments have been compressed into gists as the backtraces are quite lengthy: https://gist.github.com/Zarthus/af57be8e65675fbbc55ef692126fbdfb#file-a_op-zarthus-md

**Comment by flashcode** [comment]
Hi,
How can I reproduce the crash?
Can you try to start WeeChat without scripts? (`weechat -s`). And if this still crashes, without plugins: `weechat -p`

**Comment by Zarthus** [comment]
Reproduction steps:

1.) Update from weechat to weechat-devel
2.) Run weechat
3.) Decrypt secure.conf
4.) weechat crashes

```
[zarthus@starlight ~] $  weechat --version
1.9.1

[zarthus@starlight ~] $  sudo apt install weechat-devel
[sudo] password for zarthus:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  weechat-devel-core weechat-devel-curses weechat-devel-plugins
Suggested packages:
  weechat-devel-doc
The following packages will be REMOVED:
  weechat weechat-core weechat-curses weechat-plugins
The following NEW packages will be installed:
  weechat-devel weechat-devel-core weechat-devel-curses weechat-devel-plugins
0 upgraded, 4 newly installed, 4 to remove and 0 not upgraded.
Need to get 1,763 kB of archives.
After this operation, 439 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://weechat.org/debian stretch/main amd64 weechat-devel-core amd64 2.0-1~dev20171005 [775 kB]
Get:2 https://weechat.org/debian stretch/main amd64 weechat-devel-curses amd64 2.0-1~dev20171005 [403 kB]
Get:3 https://weechat.org/debian stretch/main amd64 weechat-devel all 2.0-1~dev20171005 [51.1 kB]
Get:4 https://weechat.org/debian stretch/main amd64 weechat-devel-plugins amd64 2.0-1~dev20171005 [534 kB]
Fetched 1,763 kB in 0s (9,518 kB/s)
(Reading database ... 79104 files and directories currently installed.)
Removing weechat (1.9.1-1) ...
Removing weechat-plugins (1.9.1-1) ...
Removing weechat-curses (1.9.1-1) ...
Removing weechat-core (1.9.1-1) ...
Selecting previously unselected package weechat-devel-core.
(Reading database ... 79029 files and directories currently installed.)
Preparing to unpack .../weechat-devel-core_2.0-1~dev20171005_amd64.deb ...
Unpacking weechat-devel-core (2.0-1~dev20171005) ...
Selecting previously unselected package weechat-devel-curses.
Preparing to unpack .../weechat-devel-curses_2.0-1~dev20171005_amd64.deb ...
Unpacking weechat-devel-curses (2.0-1~dev20171005) ...
Selecting previously unselected package weechat-devel.
Preparing to unpack .../weechat-devel_2.0-1~dev20171005_all.deb ...
Unpacking weechat-devel (2.0-1~dev20171005) ...
Selecting previously unselected package weechat-devel-plugins.
Preparing to unpack .../weechat-devel-plugins_2.0-1~dev20171005_amd64.deb ...
Unpacking weechat-devel-plugins (2.0-1~dev20171005) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up weechat-devel-core (2.0-1~dev20171005) ...
Setting up weechat-devel-curses (2.0-1~dev20171005) ...
Setting up weechat-devel-plugins (2.0-1~dev20171005) ...
Setting up weechat-devel (2.0-1~dev20171005) ...

[zarthus@starlight ~] $  weechat --version
2.0-dev


[zarthus@starlight ~] $  dpkg -l | grep weechat
rc  weechat-curses                   1.9.1-1                        amd64        Fast, light and extensible chat client - console client
ii  weechat-devel                    2.0-1~dev20171005              all          Fast, light and extensible chat client
ii  weechat-devel-core               2.0-1~dev20171005              amd64        Fast, light and extensible chat client - core files
ii  weechat-devel-curses             2.0-1~dev20171005              amd64        Fast, light and extensible chat client - console client
ii  weechat-devel-plugins            2.0-1~dev20171005              amd64        Fast, light and extensible chat client - plugins

[zarthus@starlight ~] $  weechat

*** Very bad! WeeChat is crashing (SIGSEGV received)
*** Full crash dump was saved to /home/zarthus/.weechat/weechat_crash_20171005_3
***
*** Please help WeeChat developers to fix this bug:
***   1. If you have a core file, please run:  gdb /path/to/weechat core
***      then issue command: "bt full" and send result to developers
***      (see user's guide for more info about report of crashes).
***   2. Otherwise send backtrace (below), only if it is a complete trace.
***      Keep the crash log file, just in case developers ask you some info
***      (be careful, private info like passwords may be in this file).

======= WeeChat backtrace =======
(written by WeeChat 2.0-dev (git: v1.9-353-g157dc811a), compiled on Oct  4 2017
======= End of  backtrace =======
[1]    31872 abort (core dumped)  weechat
```

weechat -s works without crashing:
```
WeeChat 2.0-dev (C) 2003-2017 - https://weechat.org/
19:00:35     │   ___       __         ______________        _____
19:00:35     │   __ |     / /___________  ____/__  /_______ __  /_
19:00:35     │   __ | /| / /_  _ \  _ \  /    __  __ \  __ `/  __/
19:00:35     │   __ |/ |/ / /  __/  __/ /___  _  / / / /_/ // /_
19:00:35     │   ____/|__/  \___/\___/\____/  /_/ /_/\__,_/ \__/
19:00:35     │ WeeChat 2.0-dev [compiled on Oct  4 2017 23:09:45]
19:00:35     │ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
19:00:35 =!= │ Error: unable to load plugin "/usr/lib/weechat/plugins/php.so": libphp7.so: cannot open shared object file: No
             │ such file or directory
19:00:35 =!= │ If you're trying to load a script and not a C plugin, try command to load scripts (/perl, /python, ...)
19:00:35     │ script: 349 scripts for WeeChat 2.0-dev
19:00:35     │ Plugins loaded: alias, aspell, buflist, charset, exec, fifo, fset, guile, irc, javascript, logger, lua, perl,
             │ python, relay, ruby, script, tcl, trigger
21:00:35     │ TZ=Europe/Amsterdam
21:00:55     │
21:00:55     │ Scripts loaded:
21:00:55     │   (none)
```

Scripts I have:
```
│WeeChat 1.9.1 (C) 2003-2017 - https://weechat.org/
│21:02:54     │ Scripts loaded:
│21:02:54     │    ia   chanmon.pl 2.5 (Channel Monitor)
│21:02:54     │    ia   highmon.pl 2.5 (Highlight Monitor)
│21:02:54     │  * ia   iset.pl 4.3 (Interactive Set for configuration options)
│21:02:54     │    ia   mass_hl_blocker.pl 0.1 (Block mass highlights)
│21:02:54     │    ia   sysinfo.pl 1.0 (provides a system info command)
│21:02:54     │    ia   topicsed.pl 0.1 (Edit channel topics by perl regular expressions or in input-line)
│21:02:54     │    ia   allquery.py 0.2 (Executes command on all irc query buffer)
│21:02:54     │    ia   autojoin.py 0.2.6 (Configure autojoin for all servers according to currently joined channels)
│21:02:54     │    ia   autosort.py 2.8 (Automatically or manually keep your buffers sorted and grouped by server.)
│21:02:54     │    ia   buffer_autoset.py 1.0 (Auto-set buffer properties when a buffer is opened)
│21:02:54     │    ia   chancomp.py 1.1 (List shared channels with user on command or WHOIS)
│21:02:54     │    ia   chanstat.py 0.1 (Channel statistics)
│21:02:54     │    ia   colorize_nicks.py 23 (Use the weechat nick colors in the chat area)
│21:02:54     │    ia N emoji2alias.py 0.1 (Replaces emoji characters with their aliases)
│21:02:54     │    ia N grep.py 0.7.7 (Search in buffers and logs)
│21:02:54     │    ia   pagetitle.py 0.5 (Adds HTML titles to http:// urls in your message.)
│21:02:54     │    ia N prism.py 0.2.10 (Taste the rainbow.)
│21:02:54     │    ia   screen_away.py 0.14 (Set away status on screen detach)
│21:02:54     │    ia   topicdiff.py 0.3 (Show differences between old and new topics.)
│21:02:54     │    ia   weestats.py 0.3 (Useless statistics about your open buffers and windows)
│21:02:54     │    ia   whois_on_query.py 0.6.1 (Whois on query)
│21:02:54     │    ia   whowas_timeago.py 1.2 (Display a human-readable time string for WHOWAS data)
│21:02:54     │    ia   myuptime.rb 0.2 (Sends machine uptime to current channel)
```

**Comment by Zarthus** [comment]
grep.py seems to crash weechat.

**Comment by Zarthus** [comment]
Crash with prism.py:
```

[zarthus@starlight ~] $  gdb /usr/bin/weechat core
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/weechat...(no debugging symbols found)...done.
[New LWP 2036]
[New LWP 2038]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `weechat -s'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f4bca3e3740 (LWP 2036))]
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {1024, 139963465684873, 0, 139963465254887,
            94714018335520, 3432, 139963468544256, 139963468547136,
            94714018337120, 139963465251634, 139963464814040, 369, 0, 3432, 0,
            139963492349760}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007f4bc89ce3fa in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x4f206e6f69737265,
            sa_sigaction = 0x4f206e6f69737265}, sa_mask = {__val = {
              3557646151409616208, 139963487019712, 94714007576784, 6048, 127,
              139963487019712, 1, 1, 0, 94714007211616, 94714007211616,
              4294967295, 0, 139963468561160, 94714006854880,
              139963492349696}}, sa_flags = 366604616, sa_restorer = 0x1}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000056245143dde2 in weechat_shutdown ()
No symbol table info available.
#3  <signal handler called>
No locals.
#4  0x00000000000751f6 in ?? ()
No symbol table info available.
#5  0x00007f4bc101cfd6 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
No symbol table info available.
#6  0x00007f4bc0fad047 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
No symbol table info available.
#7  0x00007f4bbe175d78 in ?? ()
   from /usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
No symbol table info available.
#8  0x00007f4bca1ef86a in call_init (l=0x562453126410, argc=argc@entry=2,
    argv=argv@entry=0x7ffe15d9f148, env=env@entry=0x5624536f9dc0)
    at dl-init.c:58
        init_array = <optimized out>
#9  0x00007f4bca1ef9bb in call_init (env=0x5624536f9dc0, argv=0x7ffe15d9f148,
    argc=2, l=<optimized out>) at dl-init.c:30
No locals.
#10 _dl_init (main_map=main_map@entry=0x562453e6c5f0, argc=2,
    argv=0x7ffe15d9f148, env=0x5624536f9dc0) at dl-init.c:120
        preinit_array = <optimized out>
---Type <return> to continue, or q <return> to quit---
        preinit_array_size = <optimized out>
        i = 2
#11 0x00007f4bca1f3f38 in dl_open_worker (a=a@entry=0x7ffe15d9c5d0)
    at dl-open.c:575
        args = 0x7ffe15d9c5d0
        file = <optimized out>
        mode = <optimized out>
        call_map = <optimized out>
        dst = <optimized out>
        new = <optimized out>
        __PRETTY_FUNCTION__ = "dl_open_worker"
        r = <optimized out>
        reloc_mode = <optimized out>
        nmaps = <optimized out>
        l = <optimized out>
        maps = <optimized out>
        any_tls = <optimized out>
        first_static_tls = <optimized out>
#12 0x00007f4bca1ef754 in _dl_catch_error (
    objname=objname@entry=0x7ffe15d9c5c0,
    errstring=errstring@entry=0x7ffe15d9c5c8,
    mallocedp=mallocedp@entry=0x7ffe15d9c5bf,
    operate=operate@entry=0x7f4bca1f3b50 <dl_open_worker>,
    args=args@entry=0x7ffe15d9c5d0) at dl-error.c:187
        errcode = 0
        c = {objname = 0x7ffe15d9c5c0, errstring = 0x7ffe15d9c5c8,
          malloced = 0x7ffe15d9c5bf, errcode = 0x7ffe15d9c49c, env = {{
              __jmpbuf = {140729265014496, 7267538689072314913, 2147483650,
                94714026435712, 139963392828128, 139963492483136,
                7267538689139423777, 7327572513074068001},
              __mask_was_saved = 1, __saved_mask = {__val = {139963397545480,
                  139963344061984, 139963393222924, 1, 139963392696447,
                  139963290669632, 7790834298356227072, 139963344108040,
                  140729265014232, 140729265016320, 139963344108040, 116, 1,
                  139963397545480, 139963393298806, 140729265014208}}}}}
        catchp = 0x7f4bca3e3738
        old = <optimized out>
#13 0x00007f4bca1f36e9 in _dl_open (
    file=0x562453e6a480 "/usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gn---Type <return> to continue, or q <return> to quit---
u.so", mode=-2147483646,
    caller_dlopen=0x7f4bc44fa2e0 <_PyImport_GetDynLoadFunc+288>, nsid=-2,
    argc=<optimized out>, argv=<optimized out>, env=0x5624536f9dc0)
    at dl-open.c:660
        args = {
          file = 0x562453e6a480 "/usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so", mode = -2147483646,
          caller_dlopen = 0x7f4bc44fa2e0 <_PyImport_GetDynLoadFunc+288>,
          caller_dl_open = 0x7f4bc9933ee9 <dlopen_doit+89>,
          map = 0x562453e6c5f0, nsid = 0, argc = 2, argv = 0x7ffe15d9f148,
          env = 0x5624536f9dc0}
        objname = 0x7f4bfbad8001 <error: Cannot access memory at address 0x7f4bfbad8001>
        errstring = 0x7ffe15d9c8c0 "init_hashlib"
        malloced = false
        errcode = <optimized out>
        __PRETTY_FUNCTION__ = "_dl_open"
#14 0x00007f4bc9933ee9 in dlopen_doit (a=a@entry=0x7ffe15d9c800) at dlopen.c:66
        args = 0x7ffe15d9c800
#15 0x00007f4bca1ef754 in _dl_catch_error (objname=0x5624530f3000,
    errstring=0x5624530f3008, mallocedp=0x5624530f2ff8,
    operate=0x7f4bc9933e90 <dlopen_doit>, args=0x7ffe15d9c800)
    at dl-error.c:187
        errcode = 32587
        c = {objname = 0x5624530f3000, errstring = 0x5624530f3008,
          malloced = 0x5624530f2ff8, errcode = 0x7ffe15d9c6dc, env = {{
              __jmpbuf = {0, 7327571527586560545, 140729265014784, 2, 0,
                94714026431600, 7267538689047149089, 7327572513074068001},
              __mask_was_saved = 366594240, __saved_mask = {__val = {
                  139963393277087, 206158430240, 140729265014832,
                  140729265014640, 7790834298356227072, 140729265014864, 0,
                  139963290655504, 94714026431600, 94714013343648,
                  139963397545968, 139963290655504, 139963397174880,
                  139963394384205, 139963394384332, 3}}}}}
        catchp = 0x7f4bca3e3738
        old = <optimized out>
#16 0x00007f4bc9934531 in _dlerror_run (
    operate=operate@entry=0x7f4bc9933e90 <dlopen_doit>,
    args=args@entry=0x7ffe15d9c800) at dlerror.c:163
---Type <return> to continue, or q <return> to quit---
        result = 0x5624530f2ff0
#17 0x00007f4bc9933f82 in __dlopen (file=<optimized out>, mode=<optimized out>)
    at dlopen.c:87
        args = {
          file = 0x562453e6a480 "/usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so", mode = 2, new = 0x5f,
          caller = 0x7f4bc44fa2e0 <_PyImport_GetDynLoadFunc+288>}
#18 0x00007f4bc44fa2e0 in _PyImport_GetDynLoadFunc ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#19 0x00007f4bc4571e11 in _PyImport_LoadDynamicModule ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#20 0x00007f4bc4572c61 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#21 0x00007f4bc4573fce in PyImport_ImportModuleLevel ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#22 0x00007f4bc4472318 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#23 0x00007f4bc44bf543 in PyObject_Call ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#24 0x00007f4bc45d2587 in PyEval_CallObjectWithKeywords ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#25 0x00007f4bc44662ca in PyEval_EvalFrameEx ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#26 0x00007f4bc45d315c in PyEval_EvalCodeEx ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#27 0x00007f4bc44639c9 in PyEval_EvalCode ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#28 0x00007f4bc4570b24 in PyImport_ExecCodeModuleEx ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#29 0x00007f4bc4571510 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#30 0x00007f4bc4572c61 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#31 0x00007f4bc4573fce in PyImport_ImportModuleLevel ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#32 0x00007f4bc4472318 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#33 0x00007f4bc44bf543 in PyObject_Call ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#34 0x00007f4bc45d2587 in PyEval_CallObjectWithKeywords ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#35 0x00007f4bc44662ca in PyEval_EvalFrameEx ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#36 0x00007f4bc45d315c in PyEval_EvalCodeEx ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#37 0x00007f4bc44639c9 in PyEval_EvalCode ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#38 0x00007f4bc4570b24 in PyImport_ExecCodeModuleEx ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#39 0x00007f4bc4571510 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#40 0x00007f4bc4572c61 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#41 0x00007f4bc4573fce in PyImport_ImportModuleLevel ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#42 0x00007f4bc4472318 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#43 0x00007f4bc44bf543 in PyObject_Call ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#44 0x00007f4bc45d2587 in PyEval_CallObjectWithKeywords ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#45 0x00007f4bc44662ca in PyEval_EvalFrameEx ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#46 0x00007f4bc45d315c in PyEval_EvalCodeEx ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#47 0x00007f4bc44639c9 in PyEval_EvalCode ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#48 0x00007f4bc451af6e in PyRun_FileExFlags ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#49 0x00007f4bc451c5d5 in PyRun_SimpleFileExFlags ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#50 0x00007f4bc4b86277 in weechat_python_load ()
   from /usr/lib/weechat/plugins/python.so
No symbol table info available.
#51 0x00007f4bc4b87b28 in weechat_python_command_cb ()
   from /usr/lib/weechat/plugins/python.so
No symbol table info available.
#52 0x0000562451463156 in hook_command_exec ()
No symbol table info available.
#53 0x000056245146a586 in input_exec_command ()
No symbol table info available.
#54 0x000056245146a9c4 in input_data ()
No symbol table info available.
#55 0x0000562451496eff in gui_input_return ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#56 0x0000562451441b60 in command_input ()
No symbol table info available.
#57 0x0000562451463156 in hook_command_exec ()
No symbol table info available.
#58 0x000056245146a586 in input_exec_command ()
No symbol table info available.
#59 0x000056245146a9c4 in input_data ()
No symbol table info available.
#60 0x000056245149a9f4 in gui_key_pressed ()
No symbol table info available.
#61 0x00005624514ae2cb in gui_key_flush ()
No symbol table info available.
#62 0x00005624514ae758 in gui_key_read_cb ()
No symbol table info available.
#63 0x0000562451463996 in hook_fd_exec ()
No symbol table info available.
#64 0x00005624514af25b in gui_main_loop ()
No symbol table info available.
#65 0x000056245143d757 in main ()
No symbol table info available.
```

**Comment by Zarthus** [comment]
debug libs output:
```
 Libs:
   core:
     ncurses: 6.0 (patch 20161126)
     gcrypt: 1.7.6-beta
     gnutls: 3.5.8
     curl: 7.52.1
     zlib: 1.2.8
   aspell: aspell 0.60.7-20110707
   lua: Lua 5.1
   python: 2.7.13
   perl: 5.24.1
   javascript (v8): 3.14.5.9
   guile: 2.0.13
   ruby: 2.3.3
   tcl: 8.6
````

**Comment by Zarthus** [comment]
```
WeeChat 2.0-dev (C) 2003-2017 - https://weechat.org/
19:35:32     |   ___       __         ______________        _____
19:35:32     |   __ |     / /___________  ____/__  /_______ __  /_
19:35:32     |   __ | /| / /_  _ \  _ \  /    __  __ \  __ `/  __/
19:35:32     |   __ |/ |/ / /  __/  __/ /___  _  / / / /_/ // /_
19:35:32     |   ____/|__/  \___/\___/\____/  /_/ /_/\__,_/ \__/
19:35:32     | WeeChat 2.0-dev [compiled on Oct  4 2017 23:09:45]
19:35:32     | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
19:35:32     |
19:35:32     | Welcome to WeeChat!
19:35:32     |
19:35:32     | If you are discovering WeeChat, it is recommended to read at least the quickstart guide, and the user's guide if you have some time; t
             | explain main WeeChat concepts.
19:35:32     | All WeeChat docs are available at: https://weechat.org/doc
19:35:32     |
19:35:32     | Moreover, there is inline help with /help on all commands and options (use Tab key to complete the name).
19:35:32     | The command /fset can help to customize WeeChat.
19:35:32     |
19:35:32     | You can add and connect to an IRC server with /server and /connect commands (see /help server).
19:35:32     |
19:35:32     | ---
19:35:32     |
19:35:32     | Bar "input" created
19:35:32     | Bar "title" created
19:35:32     | Bar "status" created
19:35:32     | Bar "nicklist" created
19:35:42     | Plugin "python" loaded
19:35:45     | Plugin "script" loaded
19:35:47 =!= | Error: unable to load plugin "/usr/lib/weechat/plugins/php.so": libphp7.so: cannot open shared object file: No such file or directory
19:35:47 =!= | If you're trying to load a script and not a C plugin, try command to load scripts (/perl, /python, ...)
```

// loading prism crashes at this point

**Comment by flashcode** [comment]
So the problem happens when there's no php installed (or not all required packages).
Currently the Debian packages in weechat.org repository embeds php plugin but there's a dependency problem: the php packages are not required. That means weechat can be installed without php, which causes the crash.
The solution is to install php packages.
I'm looking why it crashes though (it should not crash when the lib is not found).

**Comment by flashcode** [comment]
Hmm still not working in debian packaging.
