### ISSUE TITLE
Show in the query when NOTIFYed/MONITORed user with query connects/quits without common channels

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1102]
I seem to have a query open with one user whom with I don't have any common channels and they don't have a 24/7 connection.

When they join/quit, I am not given any kind of warning until I try to message them which fails. I think that as I have notify/monitor on them, I should either:

A) see the usual user has quit or user is back on server which I would see with query with person who is on common channels.
B) also see the notify result in the query rather than having to look at the server buffer before replying to messages.

I think A is the way to go as in my opinion B is inconsistent.

* WeeChat 2.0-dev (git: v1.9-416-g093af02) [compiled on Oct 30 2017 14:16:21]
* Debian GNU/Linux 8.9 (jessie)

**Comment by miniCruzer** [comment]
What if WeeChat does have common channels with a monitored user when they quit/join? Which quit/join line should it print, or both?

**Comment by Mikaela** [comment]
I think that optimally WeeChat would always print the same line, playing that there was a common channel with the user even if the information came from MONITOR instead of seeing the QUIT.

**Comment by miniCruzer** [comment]
I've been thinking about how to script this, and the QUIT message is easy. A script just has to check if WeeChat is in common channels with any nicknames in the notify list (and possibly cache them to avoid asking for lots of infolists). The hard part in scripting this is when the user actually (re)connects to the server.

When a user disconnects, then rejoins a common channel with WeeChat, it prints that "*nick* is back on server" message. There's no way (that I can see) for a script to eat this line if it already received an `irc_notify_joined` signal for that nickname. The `irc_notify_join` signal always comes before any `irc_in_join` signal on a server that uses MONITOR. The best a script could do is wait 5 seconds or so to see if the notify nick joined any channels. The only side effect is that if the user DOES eventually join again, after that delay, you'll get a duplicated "is back on server message" ... but that will happen anyway in the current state of WeeChat if you're PMIng a user and they suddenly join a channel.

**Comment by miniCruzer** [comment]
I was overthinking this. This unofficial script should do what you want.

https://github.com/miniCruzer/irc-scripts/blob/master/weechat/notify_print.py

This overrides the quit and join messages in query buffers for all notify list users regardless of common channels. The only drawback is you will not see their quit reason or userhost within the quit message in a buffer anymore if you have a common channel with them. But you will see quit messages like normal in common IRC buffers.

**Comment by Mikaela** [comment]
@miniCruzer you don't have issue tracker enabled, but that script keeps tracebacking, likely for recent Charybdis at PirateIRC:

```
2017-11-20T11:24:59+0200 =!= python: error in function "hide_buffer_quit_join"
2017-11-20T11:25:08+0200 python: stdout/stderr: Traceback (most recent call last):
2017-11-20T11:25:08+0200 python: stdout/stderr:   File "/home/users/mikaela/.weechat/python/autoload/notify_print.py", line 75, in hide_buffer_quit_join
2017-11-20T11:25:08+0200 python: stdout/stderr:     plugin, name, tags = modifier_data.split(";")
2017-11-20T11:25:08+0200 python: stdout/stderr: ValueError: too many values to unpack
2017-11-20T11:25:08+0200 =!= python: error in function "hide_buffer_quit_join"
2017-11-20T11:25:23+0200 python: stdout/stderr: Traceback (most recent call last):
2017-11-20T11:25:23+0200 python: stdout/stderr:   File "/home/users/mikaela/.weechat/python/autoload/notify_print.py", line 75, in hide_buffer_quit_join
2017-11-20T11:25:23+0200 python: stdout/stderr:     plugin, name, tags = modifier_data.split(";")
2017-11-20T11:25:23+0200 python: stdout/stderr: ValueError: too many values to unpack
2017-11-20T11:25:23+0200 =!= python: error in function "hide_buffer_quit_join"
2017-11-20T11:25:28+0200 python: stdout/stderr: Traceback (most recent call last):
2017-11-20T11:25:28+0200 python: stdout/stderr:   File "/home/users/mikaela/.weechat/python/autoload/notify_print.py", line 75, in hide_buffer_quit_join
2017-11-20T11:25:28+0200 python: stdout/stderr:     plugin, name, tags = modifier_data.split(";")
2017-11-20T11:25:28+0200 python: stdout/stderr: ValueError: too many values to unpack
2017-11-20T11:25:28+0200 =!= python: error in function "hide_buffer_quit_join"
2017-11-20T11:25:45+0200 python: stdout/stderr: Traceback (most recent call last):
2017-11-20T11:25:45+0200 python: stdout/stderr:   File "/home/users/mikaela/.weechat/python/autoload/notify_print.py", line 75, in hide_buffer_quit_join
2017-11-20T11:25:45+0200 python: stdout/stderr:     plugin, name, tags = modifier_data.split(";")
2017-11-20T11:25:45+0200 python: stdout/stderr: ValueError: too many values to unpack
2017-11-20T11:25:45+0200 =!= python: error in function "hide_buffer_quit_join"
2017-11-20T11:25:52+0200 python: stdout/stderr: Traceback (most recent call last):
2017-11-20T11:25:52+0200 python: stdout/stderr:   File "/home/users/mikaela/.weechat/python/autoload/notify_print.py", line 75, in hide_buffer_quit_join
2017-11-20T11:25:52+0200 python: stdout/stderr:     plugin, name, tags = modifier_data.split(";")
2017-11-20T11:25:52+0200 python: stdout/stderr: ValueError: too many values to unpack
2017-11-20T11:25:52+0200 =!= python: error in function "hide_buffer_quit_join"
2017-11-20T11:25:54+0200 python: stdout/stderr: Traceback (most recent call last):
2017-11-20T11:25:54+0200 python: stdout/stderr:   File "/home/users/mikaela/.weechat/python/autoload/notify_print.py", line 75, in hide_buffer_quit_join
2017-11-20T11:25:54+0200 python: stdout/stderr:     plugin, name, tags = modifier_data.split(";")
2017-11-20T11:25:54+0200 python: stdout/stderr: ValueError: too many values to unpack
2017-11-20T11:25:54+0200 =!= python: error in function "hide_buffer_quit_join"
2017-11-20T11:26:20+0200 python: stdout/stderr: Traceback (most recent call last):
2017-11-20T11:26:20+0200 python: stdout/stderr:   File "/home/users/mikaela/.weechat/python/autoload/notify_print.py", line 75, in hide_buffer_quit_join
2017-11-20T11:26:20+0200 python: stdout/stderr:     plugin, name, tags = modifier_data.split(";")
2017-11-20T11:26:20+0200 python: stdout/stderr: ValueError: too many values to unpack
2017-11-20T11:26:20+0200 =!= python: error in function "hide_buffer_quit_join"
2017-11-20T11:26:37+0200 python: stdout/stderr: Traceback (most recent call last):
2017-11-20T11:26:37+0200 python: stdout/stderr:   File "/home/users/mikaela/.weechat/python/autoload/notify_print.py", line 75, in hide_buffer_quit_join
2017-11-20T11:26:37+0200 python: stdout/stderr:     plugin, name, tags = modifier_data.split(";")
2017-11-20T11:26:37+0200 python: stdout/stderr: ValueError: too many values to unpack
2017-11-20T11:26:37+0200 =!= python: error in function "hide_buffer_quit_join"
```

* fi.pirateirc.net/6697 (charybdis-4-rc7)
* 2017-11-20T11:30:40+0200 -- irc: client capability, currently enabled: account-notify away-notify cap-notify extended-join multi-prefix sasl server-time userhost-in-names
* WeeChat 2.0-dev (git: v1.9-434-g338e05a) [compiled on Nov 18 2017 12:09:22]
* Debian GNU/Linux 8.9 (jessie)

**Comment by miniCruzer** [comment]
`modifier_data` likely has extra semi-colons in it. https://github.com/miniCruzer/irc-scripts/commit/3bba72405187046e7a56cdd33188eb554f0a4703 should fix it.
