### ISSUE TITLE
script: plugin "python" is not loaded

### ISSUE THREAD

**Issue by DocMAX** [weechat/weechat#1125]
hello,

whats the problem here? since some update this comes when i try to load a python script.
my env is fine:

[docmax@server]: ~>$ python --version
Python 2.7.12

regards

**Comment by DocMAX** [comment]
somehow weechat-python plugin had been uninstalled. fixed.

**Comment by flashcode** [comment]
This plugin has been added in version 2.0. The package "weechat-plugins" has been split into several packages, see the release notes: https://weechat.org/files/releasenotes/ReleaseNotes-devel.html#v2.0_debian_packaging

**Comment by jackalcooper** [comment]
i'm experiencing the same on mac
```
1.weechat│WeeChat 2.0.1 (C) 2003-2017 - https://weechat.org/
         │10:49:19     |   ___       __         ______________        _____
         │10:49:19     |   __ |     / /___________  ____/__  /_______ __  /_
         │10:49:19     |   __ | /| / /_  _ \  _ \  /    __  __ \  __ `/  __/
         │10:49:19     |   __ |/ |/ / /  __/  __/ /___  _  / / / /_/ // /_
         │10:49:19     |   ____/|__/  \___/\___/\____/  /_/ /_/\__,_/ \__/
         │10:49:19     | WeeChat 2.0.1 [compiled on Dec 21 2017 08:37:02]
         │10:49:19     | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         │10:49:19     | Plugins loaded: alias, buflist, charset, exec, fifo, fset, irc, logger, relay, script, tcl, trigger, xfer
         │10:51:17 =!= | You can not write text in this buffer
         │10:51:23 =!= | Error: unknown command "/python" (type /help for help)
```

**Comment by weechatter** [comment]
using homebrew on mac you'll have to brew the python plugin, to use it.
see FAQ: https://weechat.org/files/doc/devel/weechat_faq.en.html#compile_osx

**Comment by jackalcooper** [comment]
@weechatter Thanks, it works. Here comes another problem. I can't login with the command `/slack register [code]`
```
        │14:49:04     | python: stdout/stderr: Traceback (most recent call last):
         │14:49:04     | python: stdout/stderr:   File "/Users/jackalcooper/.weechat/python/autoload/wee_slack.py", line 115, in wrapper
         │14:49:04     | python: stdout/stderr:     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
         │14:49:04     | python: stdout/stderr:   File "/Users/jackalcooper/.weechat/python/autoload/wee_slack.py", line 3238, in slack_command_cb
         │14:49:04     | python: stdout/stderr:     EVENTROUTER.cmds[function_name]("", current_buffer, args)
         │14:49:04     | python: stdout/stderr:   File "/Users/jackalcooper/.weechat/python/autoload/wee_slack.py", line 3053, in command_register
         │14:49:04     | python: stdout/stderr:     d = json.loads(ret)
         │14:49:04     | python: stdout/stderr:   File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
         │14:49:04     | python: stdout/stderr:     return _default_decoder.decode(s)
         │14:49:04     | python: stdout/stderr:   File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
         │14:49:04     | python: stdout/stderr:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         │14:49:04     | python: stdout/stderr:   File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
         │14:49:04     | python: stdout/stderr:     raise ValueError("No JSON object could be decoded")
         │14:49:04     | python: stdout/stderr: ValueError: No JSON object could be decoded
         │14:49:04 =!= | python: error in function "slack_command_cb"
```

**Comment by flashcode** [comment]
Hi @jackalcooper,

You should better report that to the author of script here: https://github.com/wee-slack/wee-slack

**Comment by jackalcooper** [comment]
@flashcode I'm so sorry. Yeah it is the plugin's problem.
