### ISSUE TITLE
SIGSEGV crash on quit

### ISSUE THREAD

**Issue by ktsamis** [weechat/weechat#1217]
## Current behavior
It crashed after quitting and the core was dumped.

## Steps to reproduce

1. open weechat
2. quit weechat

## Desired behavior
Not crash with coredump

## Suggested solutions
No idea.

## Additional information
It was installed from opensuse Leap 15.0 main repo. It is running in tmux but it happens outside as well. It works normally just on quit it crashes. I have a few scripts, a few plugins, quite a bit configured. Let me know if you need some of that info. I think the backtrace or the log might be enough.

[weechat_crash_20180704_4469.log](https://github.com/weechat/weechat/files/2163488/weechat_crash_20180704_4469.log)

```
~> weechat                                                                                                                                                                                      

*** Very bad! WeeChat is crashing (SIGSEGV received)
*** Full crash dump was saved to /home/$user/.weechat/weechat_crash_20180704_4469.log file.
***
*** Please help WeeChat developers to fix this bug:
***   1. If you have a core file, please run:  gdb /path/to/weechat core
***      then issue command: "bt full" and send result to developers
***      (see user's guide for more info about report of crashes).
***   2. Otherwise send backtrace (below), only if it is a complete trace.
***      Keep the crash log file, just in case developers ask you some info
***      (be careful, private info like passwords may be in this file).

======= WeeChat backtrace =======
(written by WeeChat 2.1, compiled on Mar 19 2018 13:07)
001  ??:? [function weechat_backtrace]
002  ??:? [function debug_sigsegv]
003  ??:? [function __restore_rt]
which: no libpython3.6m.so.1.0 in (/usr/lib64)
addr2line: '0x1061f0': No such file
005  ??:0 [function ??]
which: no libpython3.6m.so.1.0 in (/usr/lib64)
addr2line: '0x183bdb': No such file
which: no libpython3.6m.so.1.0 in (/usr/lib64)
addr2line: '0x110658': No such file
which: no libpython3.6m.so.1.0 in (/usr/lib64)
addr2line: '0xfe56b': No such file
which: no libpython3.6m.so.1.0 in (/usr/lib64)
addr2line: '0x11121f': No such file
which: no libpython3.6m.so.1.0 in (/usr/lib64)
addr2line: '0x11c0c5': No such file
which: no libpython3.6m.so.1.0 in (/usr/lib64)
addr2line: '0x213efa': No such file
which: no libpython3.6m.so.1.0 in (/usr/lib64)
addr2line: '0x1b8302': No such file
which: no libpython3.6m.so.1.0 in (/usr/lib64)
addr2line: '0x22553a': No such file
014  ??:? [function weechat_python_unload]
015  ??:? [function weechat_python_unload_all]
016  ??:? [function plugin_script_end]
017  ??:? [function weechat_plugin_end]
018  ??:? [function plugin_unload]
019  ??:? [function plugin_unload_all]
020  ??:? [function plugin_end]
021  ??:? [function weechat_end]
022  ??:? [function main]
023  ??:? [function __libc_start_main]
024  ??:? [function _start]
======= End of  backtrace =======
Aborted (core dumped)

```
- WeeChat version: 
2.1

- OS, distribution and version: 
opensuse Leap 15.0

**Comment by weechatter** [comment]
output from "/script list" command
output from "/debug libs" command

did you try without scripts? command in terminal: weechat -s

**Comment by flashcode** [comment]
If you have the core dump, could you please send the backtrace output in gdb?
See: https://weechat.org/files/doc/devel/weechat_user.en.html#report_crashes

**Comment by ktsamis** [comment]
So trying with the ```weechat -s``` doesn't crash. I found the script that crashed it. Do you still want the backtrace of the coredump?

**Comment by flashcode** [comment]
Yes, the name of script (and its content if it's not a script from weechat.org), and the backtrace will help to fix the problem (it can be a problem in the script or in WeeChat, for now I have not enough info to say where is the problem).

**Comment by ktsamis** [comment]
I removed [this version of the script](https://github.com/weechat/scripts/pull/277) from autoload and it didn't crash. So this was the specific script that caused it. 

The backtrace:

```
tsamis@kostas:~> coredumpctl gdb                                                                                                                                                                          [63/1526]
           PID: 19883 (weechat)                                                                                                                                                                                    
           UID: 1000 (tsamis)                                                                                                                                                                                      
           GID: 100 (users)                                                                                                                                                                                       
        Signal: 6 (ABRT)     
     Timestamp: Thu 2018-07-05 13:00:36 CEST (25min ago)
  Command Line: weechat                                                                                                                                                                                           
    Executable: /usr/bin/weechat                                                                                                                                                                                  
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service                                                                                                                       
          Unit: user@1000.service                  
     User Unit: gnome-terminal-server.service                                                                                                                                                                     
         Slice: user-1000.slice
     Owner UID: 1000 (tsamis)                                                                                                                                                                                     
       Boot ID: bcb62a6a4eef4360a77ec0724f3cf94e
    Machine ID: 3c52e3fdf485bba5cdd7174658b450c9                               
      Hostname: kostas         
       Storage: /var/lib/systemd/coredump/core.weechat.1000.bcb62a6a4eef4360a77ec0724f3cf94e.19883.1530788436000000.lz4
       Message: Process 19883 (weechat) of user 1000 dumped core.

GNU gdb (GDB; openSUSE Leap 15.0) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/weechat...Reading symbols from /usr/lib/debug/usr/bin/weechat-2.1-lp150.1.4.x86_64.debug...done.
done.
[New LWP 19883]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi/auto/Fcntl/Fcntl.so
Try: zypper install -C "debuginfo(build-id)=tlFcntl.so-5.26.1-lp150.5.19.x86_64.debu"
Missing separate debuginfo for /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi/auto/POSIX/POSIX.so
Try: zypper install -C "debuginfo(build-id)=IXPOSIX.so-5.26.1-lp150.5.19.x86_64.debu"
Core was generated by `weechat'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      }
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {1024, 5045490798215916288, 0, 140055300863552, 94356006705600, 18446744073709551615, 140733098591840, 1024, 1, 140055298053942, 206158430240, 140733098591824, 140733098591616,
            5045490798215916288, 0, 140055297505624}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f612a3d16c1 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7f612b70eaa0 <gnutls_free>, sa_sigaction = 0x7f612b70eaa0 <gnutls_free>}, sa_mask = {__val = {5045490798215916288, 126, 94356041043872, 6048,
              140055317375648, 127, 1, 94351841558529, 140055314169027, 0, 5045490798215916288, 1, 5045490798215916288, 1, 1, 1}}, sa_flags = 559987144, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000055d0f839d882 in weechat_shutdown (return_code=1, crash=1) at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/core/weechat.c:621
No locals.
#3  <signal handler called>
No locals.
#4  0x00007f61249961f0 in PyErr_Restore () from /usr/lib64/libpython3.6m.so.1.0
No symbol table info available.
#5  0x00007f6120e68aba in Connection_tp_dealloc (self=0x7f61216116d0) at ../_dbus_bindings/conn.c:426
        conn = 0x55d0fbbdde50
        et = 0x0
        ev = 0x0
        etb = 0x0
        filters = <optimized out>
        object_paths = <optimized out>
#6  0x00007f6124a13bdb in subtype_dealloc () from /usr/lib64/libpython3.6m.so.1.0
No symbol table info available.
#7  0x00007f61249a0658 in dict_dealloc () from /usr/lib64/libpython3.6m.so.1.0
No symbol table info available.
#8  0x00007f612498e56b in PyDict_Clear () from /usr/lib64/libpython3.6m.so.1.0
No symbol table info available.
#9  0x00007f61249a121f in type_clear () from /usr/lib64/libpython3.6m.so.1.0
No symbol table info available.
#10 0x00007f61249ac0c5 in collect () from /usr/lib64/libpython3.6m.so.1.0
No symbol table info available.
#11 0x00007f6124aa3efa in _PyGC_CollectNoFail () from /usr/lib64/libpython3.6m.so.1.0
No symbol table info available.
#12 0x00007f6124a48302 in PyImport_Cleanup () from /usr/lib64/libpython3.6m.so.1.0
No symbol table info available.
#13 0x00007f6124ab553a in Py_EndInterpreter () from /usr/lib64/libpython3.6m.so.1.0
No symbol table info available.
#14 0x00007f6124dfd8c1 in weechat_python_unload (script=0x55d0faba9220) at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/plugins/python/weechat-python.c:966
        rc = <optimized out>
        interpreter = 0x55d0fab337c0
        filename = 0x55d0fa9e9b60 "/home/tsamis/.weechat/python/autoload/notify.py"
#15 0x00007f6124dfd995 in weechat_python_unload_all () at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/plugins/python/weechat-python.c:1015
No locals.
#16 0x00007f612569c93c in plugin_script_end (weechat_plugin=0x55d0fa91d340, plugin_data=plugin_data@entry=0x7f612502a000 <python_data>)
    at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/plugins/plugin-script.c:1747
        scripts_loaded = 1
---Type <return> to continue, or q <return> to quit---
#17 0x00007f6124dfebad in weechat_plugin_end (plugin=<optimized out>) at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/plugins/python/weechat-python.c:1582
No locals.
#18 0x000055d0f8416aa6 in plugin_unload (plugin=0x55d0fa91d340) at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/plugins/plugin.c:1204
        end_func = <optimized out>
        name = 0x55d0fa99a9e0 "python"
#19 0x000055d0f8416b59 in plugin_unload_all () at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/plugins/plugin.c:1256
        plugins_loaded = <optimized out>
#20 0x000055d0f8416e32 in plugin_end () at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/plugins/plugin.c:1379
No locals.
#21 0x000055d0f839e172 in weechat_end (gui_end_cb=0x55d0f84100e0 <gui_main_end>) at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/core/weechat.c:717
No locals.
#22 0x000055d0f839d126 in main (argc=1, argv=0x7ffefa599278) at /usr/src/debug/weechat-2.1-lp150.1.4.x86_64/src/gui/curses/normal/main.c:44
No locals.
(gdb)
(gdb) quit
```

**Comment by ktsamis** [comment]
By having the script and unloading it while it was autoloaded, it caused the weechat to crash without me quitting. I have more core dumps now if you want but I am not sure it will show anything different.

**Comment by ktsamis** [comment]
I think it's not the script itself that is the issue. It just happens to trigger the right functions in weechat itself. I reverted the script without my changes in the PR and it just showed syntax errors for the print statements. So I suspect that it would crash anyway and it's something with loading the python3 interpreter into weechat?

**Comment by flashcode** [comment]
Is there a way to reproduce the problem with default config and no script loaded?

**Comment by ktsamis** [comment]
No, it only crashes with the script loaded. I am not going to try the default config now, I would need to set up a VM for this as I'm not willing to overwrite my stuff. So not sure if you want to close this since the script causes it. If you want do so. But it seems to me that the script just triggers something in the core. Something with the python3 interpreter? No idea.

**Comment by weechatter** [comment]
you can easily run weechat with a default config : weechat -d /tmp/blafasel
This won't overwrite anything.

**Comment by flashcode** [comment]
Crash is still happening? Do you have more info about the script causing the crash?

**Comment by ktsamis** [comment]
It doesn't crash anymore, didn't crash with /upgrade for me. I tried with the default config:

> you can easily run weechat with a default config : weechat -d /tmp/blafasel
> This won't overwrite anything.
and it doesn't crash. I think I will close this issue since only the script caused the crash.
