### ISSUE TITLE
Hangs on Alacritty terminal with `alacritty-direct` set

### ISSUE THREAD

**Issue by rieje** [weechat/weechat#1701]
Hangs on Alacritty terminal with `alacritty-direct` set (cannot do anything, e.g. Ctrl+D, Ctrl+C). Alacritty's log doesn't indicate any error on its part. Runs fine with `TERM=alacritty weechat` instead.

- WeeChat version: 3.2.1
- OS, distribution and version: Arch Linux v.69
- Terminal: alacritty
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
Hi,

Thanks for your report.

I confirm the problem, and it's because the terminal reports 16M colors.
WeeChat initializes its internal palette which takes a lot of time (internal hashtable and list, which are huge).
This will require some optimizations when initializing colors.

**Comment by bitozoid** [comment]
FTR, weechat 4.4.2 crashes on RockyLinux 9 when `TERM` is set to `tmux-direct`. The terminfo is installed:

```
 $ rpm -ql ncurses-base | grep tmux-direct
/usr/share/terminfo/t/tmux-direct
```

However, it runs fine when `TERM=xterm`.

In my case, I was running alacritty, then tmux, then ssh to the RockyLinux 9 server where I was running weechat.

- Log of the crash: http://0x0.st/X0C0.log
- Backtrace of 'weechat': http://0x0.st/X0C7.txt
- Backtrace of 'weechat -t -p': http://0x0.st/X0CC.txt

Most relevant part in my opinion:

```
#0  0x00007f09d5b7594c in __pthread_kill_implementation () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f09d5b28646 in raise () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f09d5b127f3 in abort () from /lib64/libc.so.6
No symbol table info available.
#3  0x000055d740f31035 in weechat_shutdown (return_code=<optimized out>, 
    crash=<optimized out>) at /usr/src/debug/weechat-4.4.2-1.el9.x86_64/src/core/weechat.c:595
No locals.
#4  <signal handler called>
No symbol table info available.
#5  0x000055d740fbc98a in gui_color_get_pair (fg=-1, bg=-1)
    at /usr/src/debug/weechat-4.4.2-1.el9.x86_64/src/gui/curses/gui-curses-color.c:485
        index = 0
#6  0x000055d740fc9de6 in gui_window_clear (bg=<optimized out>, fg=<optimized out>, 
    window=0x55d742652fb0)
    at /usr/src/debug/weechat-4.4.2-1.el9.x86_64/src/gui/curses/gui-curses-window.c:201
        attrs = 0
        c = {attr = 476697984, chars = L"翾\001\000\x426aa2e0嗗", ext_color = 0}
        attrs = <optimized out>
        c = {attr = <optimized out>, chars = {<optimized out>, <optimized out>, 
            <optimized out>, <optimized out>, <optimized out>}, ext_color = <optimized out>}
...
```
