### ISSUE TITLE
unable to use psycopg2 in script

### ISSUE THREAD

**Issue by jacekjaros** [weechat/weechat#1756]
## Question
how to import psycopg2 to python script?

my setup:
```
$ dpkg -l weechat python3 python3-psycopg2
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version      Architecture Description
+++-================-============-============-=========================================================================
ii  python3          3.9.2-3      amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-psycopg2 2.8.6-2      amd64        Python 3 module for PostgreSQL
ii  weechat          3.4-1        all          Fast, light and extensible chat client (metapackage)
```

```
$ cat ~/.local/share/weechat/python/plog.py
import weechat
import psycopg2
```

when i try to load script i get following error:
```
python: loading script "/home/jacek/.local/share/weechat/python/plog.py"
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/home/jacek/.local/share/weechat/python/plog.py", line 2, in <module>
python: stdout/stderr (?):     import psycopg2
python: stdout/stderr (?):   File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 51, in <module>
python: stdout/stderr (?):     from psycopg2._psycopg import (                     # noqa
python: stdout/stderr (?): SystemError: initialization of _psycopg raised unreported exception
python: unable to parse file "/home/jacek/.local/share/weechat/python/plog.py"
```

when  i try to load other modules (like json or http) import is success. psycopg2 is only module i'm unable to load.

---

- WeeChat version: 3.4-1
- OS, distribution and version: Linux, Debian, bullseye

**Comment by flashcode** [comment]
Hi,

I tested on Debian Bullseye with exactly the same packages and versions, works fine for me.

Can you try with a new WeeChat config, and no other script loaded?
It could be a conflict between two scripts or two imported modules.

**Comment by jacekjaros** [comment]
hi @flashcode 

i can confirm that problem was in my setup - to be precise i was using some old script which was causing the problem.
after removing script from autoload and restarting weechat everything was start working fine.

thanks a lot for your help.
