### ISSUE TITLE
Ruby 3.x plugin API crashing

### ISSUE THREAD

**Issue by mahlonsmith** [weechat/weechat#1886]
## Bug summary

While trying to write a new plugin, I'm finding that any use of Ruby's "require" causes Weechat to crash.  After some more investigating, it appears that it crashes (with the same backtrace) when trying to eval with the `/ruby` command.

## Steps to reproduce

1. Running `weechat -d test` for a fresh environment
2. Issue `/ruby eval puts 1+1`

## Current behavior

Reducing the "load a plugin" to a minimal test case, I'm using the following skeleton:

```ruby
def weechat_init
  Weechat::register('testing', '', '', '', '', '', '')

  require 'net/http'

  return Weechat::WEECHAT_RC_OK
end
```

Results are the same irrespective of the module required.  The plugin loads fine if commenting the "require" line.

## Expected behavior

Because of issues #1865 and #1721, I'm assuming that Ruby 3 is supported, however that may be an invalid assumption (I see the User Guide explicitly mentions ruby2.7 and ruby2.7-dev as optional dependencies.)

## Additional information

```
(gdb) bt
#0  thr_kill () at thr_kill.S:4
#1  0x00000008009a4c74 in __raise (s=s@entry=6) at /usr/src/lib/libc/gen/raise.c:52
#2  0x0000000800a56109 in abort () at /usr/src/lib/libc/stdlib/abort.c:67
#3  0x0000000000249cdd in weechat_shutdown ()
#4  0x00000008037292e8 in ?? () from /usr/local/lib/libruby31.so.31
#5  0x0000000803855c0a in ?? () from /usr/local/lib/libruby31.so.31
#6  0x00000008008e158e in handle_signal (actp=actp@entry=0x805ef7140, sig=sig@entry=11, info=info@entry=0x805ef7530, ucp=ucp@entry=0x805ef71c0)
    at /usr/src/lib/libthr/thread/thr_sig.c:301
#7  0x00000008008e0b3f in thr_sighandler (sig=11, info=0x805ef7530, _ucp=0x805ef71c0) at /usr/src/lib/libthr/thread/thr_sig.c:246
#8  <signal handler called>
#9  0x0000000803738058 in ?? () from /usr/local/lib/libruby31.so.31
#10 0x00000008037354a4 in ?? () from /usr/local/lib/libruby31.so.31
#11 0x00000008037353f3 in rb_exc_raise () from /usr/local/lib/libruby31.so.31
#12 0x000000080372cbc7 in ?? () from /usr/local/lib/libruby31.so.31
#13 0x000000080372821b in rb_raise () from /usr/local/lib/libruby31.so.31
#14 0x00000008037cbc02 in ?? () from /usr/local/lib/libruby31.so.31
#15 0x00000008037cb9eb in rb_convert_type_with_id () from /usr/local/lib/libruby31.so.31
#16 0x000000080386d861 in rb_string_value_ptr () from /usr/local/lib/libruby31.so.31
#17 0x0000000803523cd1 in weechat_ruby_print_exception () from /usr/local/lib/weechat/plugins/ruby.so
#18 0x00000008035249ef in weechat_ruby_load () from /usr/local/lib/weechat/plugins/ruby.so
#19 0x0000000803525358 in weechat_ruby_command_cb () from /usr/local/lib/weechat/plugins/ruby.so
#20 0x00000000002c4c26 in hook_command_exec ()
#21 0x00000000002b1bc3 in input_exec_command ()
#22 0x00000000002b1f81 in input_data ()
#23 0x000000000026ad96 in gui_input_return ()
#24 0x0000000000289233 in command_input ()
#25 0x00000000002c4c26 in hook_command_exec ()
#26 0x00000000002b1bc3 in input_exec_command ()
#27 0x00000000002b1f81 in input_data ()
#28 0x0000000000268a8d in gui_key_pressed ()
#29 0x00000000002d7d1d in gui_key_flush ()
#30 0x00000000002d80bc in gui_key_read_cb ()
#31 0x00000000002c68ba in hook_fd_exec ()
#32 0x00000000002d8891 in gui_main_loop ()
#33 0x00000000002495a9 in main ()
```

Happy to provide any additional information.

---

- WeeChat version: 3.8
- OS, distribution and version: FreeBSD-RELEASE 13.1 (Ruby 3.1), Ubuntu 20.04 (Ruby 3.0)
- Terminal: Kitty
- Terminal multiplexer: tmux

**Comment by trygveaa** [comment]
Likely related to #1631, see this comment in particular: https://github.com/weechat/weechat/issues/1631#issuecomment-821803936

**Comment by flashcode** [comment]
I fixed the problem, but the display of exception class name is not the best we could do:

    ruby: unable to run function "script_ruby_eval"
    ruby: error: (eval):1:in `puts': no implicit conversion of Integer into String (#<Class:#<TypeError:0x00007fb4e4101698>>)
    ruby: error:      from (eval):1:in `puts'
    ruby: error:      from (eval):1:in `script_ruby_eval'
    ruby: error:      from (eval):7:in `module_eval'
    ruby: error:      from (eval):7:in `script_ruby_eval'

While it was like this with Ruby 2:

    ruby: unable to run function "script_ruby_eval"
    ruby: error: (eval):1:in `puts': no implicit conversion of Integer into String (TypeError)
    ruby: error:      from (eval):1:in `puts'
    ruby: error:      from (eval):1:in `script_ruby_eval'
    ruby: error:      from (eval):7:in `module_eval'
    ruby: error:      from (eval):7:in `script_ruby_eval'

Any help is appreciated to fix this class name, though it's not mandatory, the most important thing is that it no longer crashes.
