### ISSUE TITLE
Crash in /list

### ISSUE THREAD

**Issue by schuelermine** [weechat/weechat#2197]
### Describe the bug

/list buffer crashes when typing and scrolled down

### Steps to reproduce

1. Connect to Libera
2. Run /list
3. Press <kbd>PgDn</kbd> to scroll down a screenful
4. Type `foo` or the like

### Current behavior

Crash due to SIGSEGV handler being tripped

### Expected behavior

Just filtering based on the typed word, as is done when not scrolled down

### Additional information

Backtrace from coredump in gdb with `bt full`:

<details>

<summary> Click to expand backtrace </summary>

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {127}}
        ret = <optimized out>
#1  0x00007f55a20f7843 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
No locals.
#2  0x00007f55a20a5516 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007f55a208d935 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {0, 14726890408935098078, 93904756559808, 
              18446744073709551488, 2, 0, 93904756559808, 140005503009841, 140005767932179, 18446744073709551488, 2, 18446744073709551488, 2, 11, 
              93904756559808, 140005503009841}}, sa_flags = -1575982829, sa_restorer = 0xb}
#4  0x00005567b0c670a5 in weechat_shutdown[cold] ()
No symbol table info available.
#5  0x00007f559211a77a in rb_bug_for_fatal_signal () from /nix/store/2vg3asd3rmhng3wqvp781a1q5dhrr4yn-ruby-3.3.4/lib/libruby-3.3.4.so.3.3
No symbol table info available.
#6  0x00007f559227482b in sigsegv () from /nix/store/2vg3asd3rmhng3wqvp781a1q5dhrr4yn-ruby-3.3.4/lib/libruby-3.3.4.so.3.3
No symbol table info available.
#7  <signal handler called>
No locals.
#8  0x00007f5591f8af00 in irc_list_display_line () from /nix/store/87dpk8lydar65bxcmrxkisfyi4whvpyx-weechat-4.4.2/lib/weechat/plugins/irc.so
No symbol table info available.
#9  0x00007f5591f8b1d8 in irc_list_set_current_line () from /nix/store/87dpk8lydar65bxcmrxkisfyi4whvpyx-weechat-4.4.2/lib/weechat/plugins/irc.so
No symbol table info available.
#10 0x00007f5591f8b527 in irc_list_window_scrolled_cb () from /nix/store/87dpk8lydar65bxcmrxkisfyi4whvpyx-weechat-4.4.2/lib/weechat/plugins/irc.so
No symbol table info available.
#11 0x00005567b0cbd8c2 in hook_signal_send ()
No symbol table info available.
#12 0x00005567b0cf0335 in gui_line_free_all ()
No symbol table info available.
#13 0x00005567b0cd136e in gui_buffer_clear ()
No symbol table info available.
#14 0x00007f5591f8b0c3 in irc_list_buffer_refresh () from /nix/store/87dpk8lydar65bxcmrxkisfyi4whvpyx-weechat-4.4.2/lib/weechat/plugins/irc.so
No symbol table info available.
#15 0x00007f5591f8b9b1 in irc_list_buffer_input_data () from /nix/store/87dpk8lydar65bxcmrxkisfyi4whvpyx-weechat-4.4.2/lib/weechat/plugins/irc.so
No symbol table info available.
#16 0x00007f5591f899b3 in irc_input_data () from /nix/store/87dpk8lydar65bxcmrxkisfyi4whvpyx-weechat-4.4.2/lib/weechat/plugins/irc.so
No symbol table info available.
#17 0x00005567b0c9fd0b in input_data ()
No symbol table info available.
#18 0x00005567b0ce4e17 in gui_input_return ()
No symbol table info available.
#19 0x00005567b0c6a09f in command_input ()
No symbol table info available.
#20 0x00005567b0cb61ea in hook_command_exec ()
No symbol table info available.
#21 0x00005567b0c9f790 in input_exec_command ()
No symbol table info available.
#22 0x00005567b0c9fcbc in input_data ()
No symbol table info available.
#23 0x00005567b0ceb13b in gui_key_pressed ()
No symbol table info available.
#24 0x00005567b0d03ba2 in gui_key_flush ()
No symbol table info available.
#25 0x00005567b0d0411b in gui_key_read_cb ()
No symbol table info available.
#26 0x00005567b0cb8553 in hook_fd_exec ()
No symbol table info available.
#27 0x00005567b0d04ba5 in gui_main_loop ()
No symbol table info available.
#28 0x00005567b0c6710a in main ()
No symbol table info available.
```

</details>

NetSysFire on Libera in #weechat reports finding the source at /usr/src/debug/weechat-git/weechat/src/plugins/irc/irc-list.c:525 on their system, on this line:
```
num_spaces = server->list->name_max_length
```

### WeeChat version

4.4.2

### What OS/distribution are you using?

NixOS 24.11.20240926.1925c60 (Vicuna)

### On which terminal are you running WeeChat?

GNOME Console

**Comment by NetSysFire** [comment]
Can reproduce on 4.4.0.r28.g434c1ee-1 on Arch Linux.

Full trace:
[weechat.txt](https://github.com/user-attachments/files/17264726/weechat.txt)

Highlighted part of trace:

```
Thread 1 "weechat" received signal SIGSEGV, Segmentation fault.
irc_list_display_line (server=server@entry=0x5555561c5400, line=57) at /usr/src/debug/weechat-git/weechat/src/plugins/irc/irc-list.c:525
525     num_spaces = server->list->name_max_length
```
