### ISSUE TITLE
WeeChat IRC relay/client both hang during handshake when using SSL

### ISSUE THREAD

**Issue by GermainZ** [weechat/weechat#421]
I'm connecting from a WeeChat client to a WeeChat relay (using IRC protocol and
SSL) to three different ports/networks (9001, 9002 and 9003).

**Both the client and the relay (accessed via SSH) hang completely for a few
minutes.** After that, the client finally connects correctly (although all
messages are lost -- that is, only new messages are delivered).

(It doesn't seem to happen if there isn't a lot of missed messages to be sent, or at least if I connect shortly enough after disconnecting.)

Relay:
======

WeeChat core buffer:
--------------------

    12:09   │ relay: new client on port 9001: 1/ssl.irc.freenode/146.185.37.xxx
    12:09   │ relay: new client on port 9003: 2/ssl.irc.foonetic/146.185.37.xxx
    12:09   │ relay: new client on port 9002: 3/ssl.irc.snoonet/146.185.37.xxx
    12:10 ⚠ │ relay: TLS handshake failed for client 2/ssl.irc.foonetic/146.185.37.xxx: error -319 The operation timed out
    12:10   │ relay: disconnected from client 2/ssl.irc.foonetic/146.185.37.xxx
    12:11 ⚠ │ relay: TLS handshake failed for client 3/ssl.irc.snoonet/146.185.37.xxx: error -319 The operation timed out
    12:11   │ relay: disconnected from client 3/ssl.irc.snoonet/146.185.37.xxx

bt:
---

    # gdb $(which weechat) $(pidof weechat)
    (gdb) bt
    #0  0x00007f2ce55041b3 in select () from /usr/lib/libc.so.6
    #1  0x00007f2ce6410e85 in gnutls_system_recv_timeout () from /usr/lib/libgnutls.so.30
    #2  0x00007f2ce63f3beb in ?? () from /usr/lib/libgnutls.so.30
    #3  0x00007f2ce63f4028 in ?? () from /usr/lib/libgnutls.so.30
    #4  0x00007f2ce63ee6fc in ?? () from /usr/lib/libgnutls.so.30
    #5  0x00007f2ce63f53c0 in ?? () from /usr/lib/libgnutls.so.30
    #6  0x00007f2ce63f7efc in ?? () from /usr/lib/libgnutls.so.30
    #7  0x00007f2ce63fb570 in gnutls_handshake () from /usr/lib/libgnutls.so.30
    #8  0x00007f2ce0ecda3d in relay_client_handshake_timer_cb () from /usr/lib/weechat/plugins/relay.so
    #9  0x000000000042a067 in ?? ()
    #10 0x0000000000440f24 in ?? ()
    #11 0x00000000004048a5 in ?? ()
    #12 0x00007f2ce5443800 in __libc_start_main () from /usr/lib/libc.so.6
    #13 0x00000000004048e9 in ?? ()
    (gdb) q

Client:
=======

WeeChat server buffer:
----------------------

    ⍟ │ irc: connecting to server xxx/9002 (SSL)...
    ⚠ │ irc: TLS handshake failed
    ⚠ │ irc: error: The operation timed out

bt:
---

    # gdb $(which weechat) $(pidof weechat)
    (gdb) bt
    #0  0x00007f87447d21b3 in select () from /usr/lib/libc.so.6
    #1  0x00007f87456dee85 in gnutls_system_recv_timeout () from /usr/lib/libgnutls.so.30
    #2  0x00007f87456c1beb in ?? () from /usr/lib/libgnutls.so.30
    #3  0x00007f87456c2028 in ?? () from /usr/lib/libgnutls.so.30
    #4  0x00007f87456bc6fc in ?? () from /usr/lib/libgnutls.so.30
    #5  0x00007f87456c33c0 in ?? () from /usr/lib/libgnutls.so.30
    #6  0x00007f87456c5efc in ?? () from /usr/lib/libgnutls.so.30
    #7  0x00007f87456c7efb in gnutls_handshake () from /usr/lib/libgnutls.so.30
    #8  0x000000000042edd4 in ?? ()
    #9  0x0000000000427572 in ?? ()
    #10 0x0000000000440fce in ?? ()
    #11 0x00000000004048a5 in ?? ()
    #12 0x00007f8744711800 in __libc_start_main () from /usr/lib/libc.so.6
    #13 0x00000000004048e9 in ?? ()
    (gdb) q

**Comment by clawoflight** [comment]
I'm having what appears to be the same issue on Debian buster.
