### ISSUE TITLE
Crash due to guile plugin in gnutls when weechat exits

### ISSUE THREAD

**Issue by ronin13** [weechat/weechat#779]
Earlier reported in https://github.com/weechat/weechat/issues/527#issuecomment-239466835: 

This is a repeatable crash with latest git HEAD as well as well as v1.6-dev tag. Disabling guile plugin with --disable-guile in configure prevents crash.

It is crashing in a free() in gnutls during exit.

```

#0  x86_64_fallback_frame_state (context=0x7ffc0839a850, context=0x7ffc0839a850, fs=0x7ffc0839a940) at ./md-unwind-support.h:58
#1  uw_frame_state_for (context=context@entry=0x7ffc0839a850, fs=fs@entry=0x7ffc0839a940) at /build/gcc-multilib/src/gcc/libgcc/unwind-dw2.c:1249
#2  0x00007f8e365cd6d8 in _Unwind_Backtrace (trace=0x7f8e3e2ea820 <backtrace_helper>, trace_argument=0x7ffc0839ab00) at /build/gcc-multilib/src/gcc/libgcc/unwind.inc:290
#3  0x00007f8e3e2ea98f in backtrace () from /usr/lib/libc.so.6
#4  0x000000000045344d in weechat_backtrace () at wee-backtrace.c:167
#5  0x000000000042ba6d in debug_sigsegv () at wee-debug.c:181
#6  <signal handler called>
#7  0x00007f8e380f57a0 in ?? ()
#8  0x00007f8e3ec00209 in ?? () from /usr/lib/libgnutls.so.30
#9  0x00007f8e3eb54062 in ?? () from /usr/lib/libgnutls.so.30
#10 0x00007f8e3eb65d52 in gnutls_pubkey_deinit () from /usr/lib/libgnutls.so.30
#11 0x00007f8e3eb6569c in gnutls_pcert_deinit () from /usr/lib/libgnutls.so.30
#12 0x00007f8e3ebcb3f6 in ?? () from /usr/lib/libgnutls.so.30
#13 0x00007f8e3eb5e290 in gnutls_deinit () from /usr/lib/libgnutls.so.30
#14 0x00007f8e3ab2f5c6 in irc_server_close_connection (server=0x2533d20) at irc-server.c:3218
#15 0x00007f8e3ab34cf4 in irc_server_disconnect (server=0x2533d20, switch_address=0, reconnect=0) at irc-server.c:4690
#16 0x00007f8e3ab350a3 in irc_server_disconnect_all () at irc-server.c:4763
#17 0x00007f8e3aac9e9c in weechat_plugin_end (plugin=0x24c2f70) at irc.c:290
#18 0x0000000000455a73 in plugin_unload (plugin=0x24c2f70) at plugin.c:1160
#19 0x0000000000455ba9 in plugin_unload_all () at plugin.c:1212
#20 0x0000000000455edf in plugin_end () at plugin.c:1335
#21 0x0000000000405b28 in weechat_end (gui_end_cb=0x49c1fa <gui_main_end>) at weechat.c:717
#22 0x00000000004047ff in main (argc=1, argv=0x7ffc0839b7d8) at main.c:42

```

Should be simple to reproduce. 

I configured as follows:

```

Enabled features:
   Interfaces............. : ncurses
   Plugins................ : alias aspell(aspell) charset exec fifo irc logger relay script perl(5.24.0) python(2.7) ruby(2.3.0) lua(5.3.3) guile(2.0.12) trigger xfer
   Optional features...... : gnutls flock largefile backtrace
   Compile with debug..... : yes
   Compile tests.......... : no
   Man page............... : no
   Documentation.......... : no
   Certificate authorities : /etc/ssl/certs/ca-certificates.crt

Disabled features:
   - not asked: tests man doc
   - not found: tcl javascript/v8

WeeChat home directory is ~/.weechat

WeeChat will be installed in /usr/bin

configure complete, now type 'make' to build WeeChat 1.6-dev

```

Build flags: 

```

echo "$CFLAGS \n $CXXFLAGS"
-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong
 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong

```

**Comment by flashcode** [comment]
Could you please test the current devel version (2.7-dev), which now supports Guile 2.2, and then test with this version of Guile?

**Comment by flashcode** [comment]
Closing old issue, not reproduced.
